#!/usr/bin/env bash

function main() {
  # ヘルプ表示
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'show_DuplicateLine Ver1.00'
    echo '  ファイル内の重複行を指定された方法で表示'
    echo '  show_DuplicateLine [オプション] [ファイル] '
    echo '    [オプション]'
    echo '      -d   重複行を削除して表示'
    echo '      -a   重複行だとしても1度目は表示し、それ以降の重複は削除して表示'
    echo '      -c   テキストはそのままで重複回数を表示'
    echo '      -o   重複行のみを表示'
    echo '    省略   重複行を削除して表示'
    echo ''
    echo 'Copyright (c) 2020 kirakira  License: MIT'
    return
  fi

  # オプション処理
  if [ -e "$1" ]; then
    _f="$1"; _proc="";
  else
    if [ ! -e "$2" ]; then echo "あのぉ～ファイル存在しませんけど～！！"; return; fi
    if [ -d "$2" ]; then echo "ファイル指定して欲しいんですけど～！！"; return; fi
    _f="$2"; _proc="$1";
  fi


  # 重複行でも1回目は表示
  if [ "$_proc" = "-a" ]; then awk '!a[$0]++' "$_f"; return; fi;

  # その他のオプション
  cat "$_f" | awk -v proc="$_proc" '

    BIGIN { i = 0 }

    {
      dat[i++] = $0 # 行番号をキーとした全行
      count[$0]++   # 行内容をキーとして重複回数
    }

    END {
      switch(proc){
        case "-c":
          # 重複回数を表示(-c)
          for(j=0; j < i; j++) { printf "%6d│ %s\n", count[dat[j]], dat[j] }
          break
        case "-o":
          # 重複行のみを表示(-o)
          for(j=0; j < i; j++) { if (count[dat[j]] != "1") {print dat[j]} }
          break
        default:
          # 重複行を削除して表示(-d or その他)
          for(j=0; j < i; j++) { if (count[dat[j]] == "1") {print dat[j]} }
          break
      }
    }
  '
}

main "$@"
